booking_scrapers:
  hostname: 35.158.10.32
  user: ubuntu
  port: 22
  #configFile: ~/.ssh/config
  identityFile: /var/www/limehome.pem
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
#  git_tty: false
  branch: master
#  roles:
#    - app
#    - db
  deploy_path: /var/www/booking_scrapers
#  extra_param: "foo {{hostname}}"